import type { Agent } from "@/components/agents/AgentCard"

export const mockAgents: Agent[] = [
  { id: "1", name: "CodeMaster Pro", description: "Advanced AI coding assistant specializing in full-stack development, code review, and architecture design.", location: { city: "San Francisco", country: "USA", lat: 37.7749, lng: -122.4194 }, skills: ["coding", "ai", "automation", "devops"], status: "online", rating: 4.9, tasksCompleted: 12847, createdAt: "2024-01-15" },
  { id: "2", name: "DataWiz", description: "Expert data analyst and visualization specialist. Transforms raw data into actionable insights.", location: { city: "London", country: "UK", lat: 51.5074, lng: -0.1278 }, skills: ["data", "ai", "automation"], status: "online", rating: 4.8, tasksCompleted: 8923, createdAt: "2024-02-20" },
  { id: "3", name: "DesignBot", description: "Creative AI assistant for UI/UX design, brand identity, and visual content creation.", location: { city: "Tokyo", country: "Japan", lat: 35.6762, lng: 139.6503 }, skills: ["design", "vision", "ai"], status: "busy", rating: 4.7, tasksCompleted: 6542, createdAt: "2024-03-10" },
  { id: "4", name: "WebScraper X", description: "Powerful web scraping and data extraction agent. Handles complex websites with ease.", location: { city: "Berlin", country: "Germany", lat: 52.5200, lng: 13.4050 }, skills: ["web", "automation", "data"], status: "online", rating: 4.6, tasksCompleted: 15632, createdAt: "2024-01-05" },
  { id: "5", name: "ChatGenius", description: "Conversational AI for customer support, lead generation, and community management.", location: { city: "Sydney", country: "Australia", lat: -33.8688, lng: 151.2093 }, skills: ["chat", "writing", "ai"], status: "online", rating: 4.9, tasksCompleted: 23456, createdAt: "2023-12-01" },
  { id: "6", name: "SecurityBot", description: "Cybersecurity specialist for vulnerability scanning, penetration testing, and security audits.", location: { city: "Tel Aviv", country: "Israel", lat: 32.0853, lng: 34.7818 }, skills: ["security", "devops", "automation"], status: "offline", rating: 4.8, tasksCompleted: 3421, createdAt: "2024-04-15" },
  { id: "7", name: "ContentWriter", description: "Professional content creation agent for blogs, marketing copy, and technical documentation.", location: { city: "Toronto", country: "Canada", lat: 43.6532, lng: -79.3832 }, skills: ["writing", "ai", "chat"], status: "online", rating: 4.5, tasksCompleted: 7834, createdAt: "2024-02-28" },
  { id: "8", name: "VisionAI", description: "Computer vision specialist for image analysis, object detection, and visual search.", location: { city: "Singapore", country: "Singapore", lat: 1.3521, lng: 103.8198 }, skills: ["vision", "ai", "data"], status: "busy", rating: 4.7, tasksCompleted: 4521, createdAt: "2024-03-22" },
  { id: "9", name: "AutomationHub", description: "Workflow automation expert. Connects APIs, automates tasks, and builds integrations.", location: { city: "Amsterdam", country: "Netherlands", lat: 52.3676, lng: 4.9041 }, skills: ["automation", "coding", "devops"], status: "online", rating: 4.6, tasksCompleted: 9876, createdAt: "2024-01-20" },
  { id: "10", name: "AudioMaster", description: "Audio processing and music generation AI. Creates soundtracks, podcasts, and audio effects.", location: { city: "Los Angeles", country: "USA", lat: 34.0522, lng: -118.2437 }, skills: ["audio", "ai", "automation"], status: "online", rating: 4.4, tasksCompleted: 2345, createdAt: "2024-05-01" },
  { id: "11", name: "DevOpsNinja", description: "Infrastructure automation, CI/CD pipelines, and cloud deployment specialist.", location: { city: "Seattle", country: "USA", lat: 47.6062, lng: -122.3321 }, skills: ["devops", "automation", "security"], status: "online", rating: 4.8, tasksCompleted: 5678, createdAt: "2024-02-14" },
  { id: "12", name: "MLEngineer", description: "Machine learning model development, training, and deployment at scale.", location: { city: "Paris", country: "France", lat: 48.8566, lng: 2.3522 }, skills: ["ai", "data", "coding"], status: "offline", rating: 4.7, tasksCompleted: 3210, createdAt: "2024-03-30" },
]
